### ISSUE TITLE
Inquiry: Pruning process without spatial decomposition? 

### ISSUE THREAD

**Issue by slothkong** [yihui-he/channel-pruning#34] opened 2017-10-12 12:28 UTC
Thanks again for sharing your code and releasing the  VGG-16 5X pruned caffemodel. May I ask how much should the code be changed in order to produce this model (pruning only, no 3C included) ? 

Can this be done by simply passing a different flag instead of "-action c3"?  Thanks!!!! And sorry for asking but I'm sure a lot of people will want to know about this.

**Comment by yihui-he** [comment] 2017-10-12 15:23
The code was rewrite once, I need to adapt it to current released code. 
actually you can implement it yourself, just delete VH and ITQ in R3 function. 
Duplicate of #16

**Comment by slothkong** [comment] 2017-10-13 01:30
Thanks!!!

**Closed** 2017-10-13 01:29 UTC

**Comment by OPPOA113** [comment] 2017-10-25 03:10
@slothkong 
Hi
Have you successfully changed the code for pruning only?And what should be modify.

**Comment by slothkong** [comment] 2017-10-25 12:12
@OPPOA113  I'm working on it right now. I also want to modify the code to support other DNNs .  I think what @yihui-he  was talking about can be found in https://github.com/yihui-he/channel-pruning/blob/e8a5fe0b97eaf5de693cc93a9d1024fdf919dab8/lib/net.py#L1343  and https://github.com/yihui-he/channel-pruning/blob/e8a5fe0b97eaf5de693cc93a9d1024fdf919dab8/lib/net.py#L1376 . Changing those two  "if-conditions" to "False" might be the solution.

**Comment by slothkong** [comment] 2017-10-26 00:22
@OPPOA113 , seems like the "channel pruning" on  "channel decomposition" ㅜㅜ.  There is a set of additional layer names `conv_H`, `conv_V` and `conv_P` https://github.com/yihui-he/channel-pruning/blob/e8a5fe0b97eaf5de693cc93a9d1024fdf919dab8/lib/net.py#L1334-L1336 

We are not interested in `conv_H` or `conv_V,` only `conv_P.`  However, `conv_P` is introduced in the new model `self.WPQ`  when we execute "channel decomposition" ( calling the function  `ITQ_decompose()` yields the following values:  `W1`, `W2`, `B`, `W12`)

https://github.com/yihui-he/channel-pruning/blob/e8a5fe0b97eaf5de693cc93a9d1024fdf919dab8/lib/net.py#L1388-L1392

Finally, in "channel pruning", we use `conv_P` to set self.WPQ

https://github.com/yihui-he/channel-pruning/blob/e8a5fe0b97eaf5de693cc93a9d1024fdf919dab8/lib/net.py#L1414-L1419

TLD: we have find a way to define  `W2` without executing `ITQ_decompose()` . 
@yihui-he, if you are reading this, please comment^^

**Comment by OPPOA113** [comment] 2017-10-26 04:02
@slothkong 
thanks,how it was  going on ,it work finally?  actually, i do not understand the code completely.
 if you have finish,please let me know. thank you !! i will follow you work!

**Comment by slothkong** [comment] 2017-10-26 09:07
@OPPOA113 still not working, I did this:
`P_shape = [W2.shape[0], W2.shape[1], 1, 1]`
`self.WPQ[(conv_P, 0)] = W2.reshape(P_shape)`
But I get and error because W2 is too big to be reshaped. Im not sure what should I change.

**Comment by slothkong** [comment] 2017-11-05 16:17
@OPPOA113 OK, I think I finally understood the code. When @yihui-he  says he did not change the .caffemodel dynamically, he means that when pruning a layer, he sets the value of the selected filter channels  to zero (shape of the kernel matrix is unchanged). Also, a reshaped copy of the weights is added to the `WPQ` dict `(WPQ` will be used to modify the model in `stepend()`). For all intents and purposes, executing forward pass using the weights with new added zeros will yield the same error as doing so on a smaller matrix, but with the benefit that we dont have to worry about the new matrix dimensions not matching with the next layer. 
I dont have access to my workstation at the time being, so I havent been able to test the pruning kernel. But It looks like this: 

    `def stepR1(net,conv,convnext,d_c,finish=False):
       '''channel pruning '''
       convs = net.convs # copy the list with conv layer names
       if conv in pooldic:
           X_name = net.bottom_names[convnext][0]
       else:
           X_name = conv
       # newX: N c h w (BatchSize, channels, h, w), W2: n c h w (out_channels, in_channels, fitler_h, filter_w)
       idxs, W2, B2 = net.dictionary_kernel(X_name, None, d_c, convnext, None, DEBUG=1)
       # W2
       net.selection[convnext] = idxs
       net.param_data(convnext)[:, ~idxs, ...] = 0
       net.param_data(convnext)[:, idxs, ...] = W2.copy()
       net.set_param_b(convnext,B2)
       # W1
       net.WPQ[(conv,0)] = net.WPQ[(conv,0)][idxs]
       net.WPQ[(conv,1)] = net.WPQ[(conv,1)][idxs]
       net.set_conv(conv, num_output=sum(idxs))
    
       return {"net":net}`

I moved some variable definitions outside, and run the for-loop externally. Once I have tested it I will upload the full code to my for ^^.

**Comment by YaoZhongtian** [comment] 2018-06-28 06:03
@slothkong Sorry to bother you, would you like to tell me whether you implement it ?

**Comment by slothkong** [comment] 2018-06-29 19:37
@YaoZhongtian I was unable to debug it. Seems like I never fully understood how @yihui-he's code worked. So even thought I managed to prune the hold model and write the protobuf file, it's accuracy was awefully bad.

**Comment by YaoZhongtian** [comment] 2018-06-30 05:30
@slothkong Thank for your reply. I just started trying to solve it.

**Comment by Tveek** [comment] 2018-07-09 08:41
@YaoZhongtian any solution for this?

**Comment by YaoZhongtian** [comment] 2018-07-09 10:48
@Tveek Actually, I can't understand the code completely. Just waiting for the author to release the code of this part.

**Comment by bbjy** [comment] 2018-07-13 08:47
Is there anyone know how the speed-up is determined? And what is the relationship between the speed-up ratio and the corresponding channel preserved ratio?Thank you!
