### ISSUE TITLE
how can i Turn   cb_3c_3C4x_mem_bn_vgg.prototxt   into    channel_pruning.prototxt ?

### ISSUE THREAD

**Issue by alexqiaodan** [yihui-he/channel-pruning#80] opened 2018-02-03 08:59 UTC
how can i Turn   cb_3c_3C4x_mem_bn_vgg.prototxt   into    channel_pruning.prototxt ?

**Comment by alexqiaodan** [comment] 2018-02-03 09:00
how can i turn cb_3c_3C4x_mem_bn_vgg.prototxt into channel_pruning.prototxt ?

**Comment by yihui-he** [comment] 2018-11-28 20:23
Duplicate of #16

**Closed by yihui-he** 2018-11-28 20:23 UTC
