### ISSUE TITLE
trian error

### ISSUE THREAD

**Issue by LXWDL** [yihui-he/channel-pruning#22] opened 2017-09-27 14:18 UTC
Hi,When I run the python3 train.py -action c3 -caffe GPU0,I encounted the following error:
/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py:18: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "
no lighting pack
Failed to include caffe_pb2, things might go wrong!
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1062, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1084, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from lib.net import Net, load_layer, caffe_test
  File "/home/dl/file/lxw/channel_pruning/channel-pruning-master/lib/net.py", line 7, in <module>
    import caffe
  File "/home/dl/file/lxw/channel_pruning/channel-pruning-master/caffe/python/caffe/__init__.py", line 4, in <module>
    from .proto.caffe_pb2 import TRAIN, TEST
  File "/home/dl/file/lxw/channel_pruning/channel-pruning-master/caffe/python/caffe/proto/caffe_pb2.py", line 799, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/descriptor.py", line 869, in _ParseOptions
    message.ParseFromString(string)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1068, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

I have no idea how to solver this problems,Thanks for your help！

**Comment by yihui-he** [comment] 2017-09-27 15:05
Duplicate of #12 #13

**Closed by yihui-he** 2017-09-27 15:05 UTC
