### ISSUE TITLE
PYTHON_LIBRARIES ?= boost_python python3.4

### ISSUE THREAD

**Issue by cicido** [yihui-he/channel-pruning#65] opened 2017-11-15 12:40 UTC
I found the following configuration in the Makefile:
PYTHON_LIBRARIES ?= boost_python python3.4
it seems not compatible if user does not configure the variable PYTHON_LIBRARIES in the Makefile.config or use python2. and In BLVC caffe  it is boost_python python2.7.
this prone to error.

**Comment by yihui-he** [comment] 2017-11-15 18:40
Duplicate of #57

**Closed by yihui-he** 2017-11-15 18:40 UTC
