### ISSUE TITLE
some kind of issue when python3 train.py -action c3 -caffe 0

### ISSUE THREAD

**Issue by HoboChen** [yihui-he/channel-pruning#13] opened 2017-09-18 10:33 UTC
hello, i have no idea what is wrong. thanks in advance

done:
git clone --recursive https://github.com/yihui-he/channel-pruning.git
make -j8 && make pycaffe

fail:
python3 train.py -action c3 -caffe 0

stdout:

no lighting pack
Failed to include caffe_pb2, things might go wrong!
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1069, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1091, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from lib.net import Net, load_layer, caffe_test
  File "/home/t-jinche/channel-pruning/lib/net.py", line 7, in <module>
    import caffe
  File "/home/t-jinche/channel-pruning/caffe/python/caffe/__init__.py", line 4, in <module>
    from .proto.caffe_pb2 import TRAIN, TEST
  File "/home/t-jinche/channel-pruning/caffe/python/caffe/proto/caffe_pb2.py", line 799, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/descriptor.py", line 874, in _ParseOptions
    message.ParseFromString(string)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1075, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

**Comment by yihui-he** [comment] 2017-09-18 15:23
Duplicate of #12

**Comment by yihui-he** [comment] 2017-09-18 16:00
According to https://github.com/BVLC/caffe/issues/2464, this problem is solved in latest Caffe version. Since I can't reproduce this problem, I've merge my Caffe to the latest BVLC/caffe. Please update and try remake.

**Closed** 2017-09-20 04:50 UTC

**Comment by cateweb** [comment] 2018-07-09 05:38
solved with sudo pip3 install sklearn-contrib-lightning
