### ISSUE TITLE
how to deal with the trained model of faster rcnn?(vgg)

### ISSUE THREAD

**Issue by liangzz1991** [yihui-he/channel-pruning#25] opened 2017-09-29 09:21 UTC
All are welcome to create issues, but please google the problem first, and make sure it has not already been reported.

### What hardware and operating system/distribution are you running?
Operating system:  
CUDA version:  
CUDNN version:  
openCV version:  
BLAS:  
Python version:

**Comment by yihui-he** [comment] 2017-09-29 15:27
Temporarily, we only release the code for VGG-16 3C 4X, due to non-technical issue. You could implement it yourself by following the paper. 
Duplicate of #11

**Comment by yihui-he** [comment] 2017-10-10 21:25
https://github.com/yihui-he/channel-pruning#pruning-faster-rcnn

**Closed by yihui-he** 2017-10-10 21:25 UTC
