### ISSUE TITLE
about rankdic

### ISSUE THREAD

**Issue by cicido** [yihui-he/channel-pruning#69] opened 2017-12-06 02:18 UTC
thank for sharing your code. I have been trace your code with PDB.  but I don't know how did you get the numbers as 17, 17,37, 47 etc
rankdic = {'conv1_1': 17,
                   'conv1_2': 17,
                   'conv2_1': 37,
                   'conv2_2': 47,
                   'conv3_1': 83,
                   'conv3_2': 89,
                   'conv3_3': 106,
                   'conv4_1': 175,
                   'conv4_2': 192,
                   'conv4_3': 227,
                   'conv5_1': 398,
                   'conv5_2': 390,
                   'conv5_3': 379}

**Comment by yihui-he** [comment] 2017-12-06 02:30
Duplicate of #30 #47

**Closed by yihui-he** 2017-12-06 02:30 UTC

**Comment by yanyanxixi** [comment] 2017-12-06 02:41
hi 
 i want to channel pruning the resnet model 
i slso have the problem that i cant understand the function R3(),
my convs is [conv1
res2a_branch1
res2a_branch2a
res2a_branch2b
res2b_branch2a
res2b_branch2b
res3a_branch1
res3a_branch2a
res3a_branch2b
res3b_branch2a
res3b_branch2b
res4a_branch1
res4a_branch2a
res4a_branch2b
res4b_branch2a
res4b_branch2b
res5a_branch1
res5a_branch2a
res5a_branch2b
res5b_branch2a
res5b_branch2b]

then use the "rank = rankdic[conv]" means that my rankdic must contain the whole convs, right?
and how to set the alldic and pooldic too?
hope your replay!
thanks a lot

**Comment by yihui-he** [comment] 2017-12-06 02:44
@yanyanxixi Duplicate of #30
